### ISSUE TITLE
Upload fails with binstar NotFound error

### ISSUE THREAD

**Issue by jitseniesen** [conda-forge/spyder-unittest-feedstock#6]
I am trying to update the conda package from 0.1.1 to 0.2.0 (PR #4). For some reason, the CI servers do not upload the package to the Anaconda servers. The tests on the pull requests are all fine, but the merge commit yields an error.

The relevant part of the log is (see [here](https://circleci.com/gh/conda-forge/spyder-unittest-feedstock/15?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) for the complete log):

```
+ upload_or_check_non_existence /recipe_root conda-forge --channel=main
Using Anaconda API: https://api.anaconda.org
Using Anaconda API: https://api.anaconda.org
[ERROR] 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/binstar_client/commands/upload.py", line 133, in add_release
    aserver_api.release(username, package_name, version)
  File "/opt/conda/lib/python3.6/site-packages/binstar_client/__init__.py", line 377, in release
    self._check_response(res)
  File "/opt/conda/lib/python3.6/site-packages/binstar_client/__init__.py", line 216, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.NotFound: ("release version=u'0.2.0' does not exist", 404)
```

I tried re-rendering using conda-smithy (PR #5) but that did not help.

@ccordoba12 @goanpeca Do you have any idea what the matter is?

**Comment by ccordoba12** [comment]
Yes, you need to readd this feedstock in staged-recipes to get a new upload token for it.

Please take a look at

conda-forge/staged-recipes#3537

to see how to do it.

**Comment by jitseniesen** [comment]
> Yes, you need to readd this feedstock in staged-recipes to get a new upload token for it.

Thanks, after waiting a while that did the trick. Rather annoying that I could not find anything about this myself.

**Comment by ccordoba12** [comment]
I had to ask about in the conda-forge gitter channel myself, so it was not easy to find.
